version: '3.7'

services:
  postgres:
    image: bitnami/postgresql:latest
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - authJs_prisma_template:/var/lib/postgresql/data

volumes:
  authJs_prisma_template: 